name: type_controller
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  window_manager: ^0.4.0
  web_socket_channel: ^3.0.1
  uuid: ^4.4.2
  hotkey_manager: ^0.2.3
  intl: ^0.19.0
  url_launcher: ^6.3.0
  flutter_colorpicker: ^1.1.0
  bitsdojo_window: ^0.1.6
  file_picker: ^8.1.2
  path_provider: ^2.1.4
  mime: ^1.0.6

  path: any
  ffi: ^2.1.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  sqflite_common_ffi: ^2.3.3
  ffigen: ^14.0.1

flutter:
  uses-material-design: true
  fonts:
    - family: SourceHanSerifCN-Regular
      fonts:
        - asset: assets/fonts/SourceHanSerifCN-Regular.otf

ffigen:
  output: 'lib/native/libEchoLiveMsgAPIConvert.dart'
  headers:
    entry-points:
      - 'lib/native/libEchoLiveMsgAPIConvert.h'